#!/bin/bash
#
# CraftGenie OneDev development launcher.
#
# Runs OneDev locally against PostgreSQL in Docker instead of the bundled HSQLDB,
# so development and production use the same database engine, and adds pgAdmin
# with the connection already registered.
#
# OneDev itself stays on the host under ../dev.sh - putting it in a container would
# cost the hot class reloading that makes the dev loop usable.
#
#   ./cg-dev.sh up        start PostgreSQL + pgAdmin
#   ./cg-dev.sh run       up, point OneDev at PostgreSQL, then start OneDev
#   ./cg-dev.sh psql      psql shell on the OneDev database
#
# Run ./cg-dev.sh with no arguments for the full command list.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEV_DIR="$ROOT/craftgenie-dev"
RUNTIME_DIR="$DEV_DIR/.runtime"
ENV_FILE="$DEV_DIR/.env"
COMPOSE_FILE="$DEV_DIR/docker-compose.yml"
SANDBOX_CONF="$ROOT/server-product/target/sandbox/conf"
TEMPLATE_CONF="$ROOT/server-product/system/conf/hibernate.properties"

if [ -t 1 ]; then
	BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
	YELLOW=$'\033[33m'; BLUE=$'\033[34m'; RESET=$'\033[0m'
else
	BOLD=""; DIM=""; RED=""; GREEN=""; YELLOW=""; BLUE=""; RESET=""
fi

info() { printf '%s==>%s %s\n' "$BLUE" "$RESET" "$*"; }
ok()   { printf '%s  ok%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%s warn%s %s\n' "$YELLOW" "$RESET" "$*" >&2; }
die()  { printf '%serror%s %s\n' "$RED" "$RESET" "$*" >&2; exit 1; }

# --------------------------------------------------------------------------------
# Environment
# --------------------------------------------------------------------------------

require_docker() {
	command -v docker >/dev/null 2>&1 || die "docker is not installed or not on PATH"
	docker compose version >/dev/null 2>&1 \
		|| die "docker compose v2 is required (got: $(docker --version))"
	docker info >/dev/null 2>&1 \
		|| die "the docker daemon is not reachable - is Docker running?"
}

load_env() {
	if [ ! -f "$ENV_FILE" ]; then
		info "No .env found, creating one from .env.example"
		cp "$DEV_DIR/.env.example" "$ENV_FILE"
		ok "Created $ENV_FILE - edit it if the defaults do not suit you"
	fi
	# set -a exports everything the file assigns, which is what compose and psql need.
	set -a
	# shellcheck disable=SC1090
	. "$ENV_FILE"
	set +a

	: "${POSTGRES_DB:=onedev}"
	: "${POSTGRES_USER:=onedev}"
	: "${POSTGRES_PORT:=6432}"
	: "${PGADMIN_EMAIL:=dev@craftgenie.local}"
	: "${ONEDEV_INITIAL_USER:=admin}"
	: "${ONEDEV_INITIAL_EMAIL:=admin@craftgenie.local}"
	: "${ONEDEV_SERVER_URL:=http://localhost:6610}"
	: "${PGADMIN_PORT:=6680}"
	[ -n "${POSTGRES_PASSWORD:-}" ] || die "POSTGRES_PASSWORD is not set in $ENV_FILE"
	[ -n "${PGADMIN_PASSWORD:-}" ] || die "PGADMIN_PASSWORD is not set in $ENV_FILE"
}

compose() { docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"; }

# --------------------------------------------------------------------------------
# Generated runtime files
#
# pgpass and servers.json both carry values from .env, so they are generated rather
# than committed. That keeps the credentials in exactly one place and keeps them
# out of git.
# --------------------------------------------------------------------------------

write_runtime_files() {
	mkdir -p "$RUNTIME_DIR"

	# Host and port as pgAdmin sees them: inside the compose network, not the
	# published port. Using 6432 here would fail from inside the container.
	printf 'postgres:5432:%s:%s:%s\n' \
		"$POSTGRES_DB" "$POSTGRES_USER" "$POSTGRES_PASSWORD" > "$RUNTIME_DIR/pgpass"
	chmod 600 "$RUNTIME_DIR/pgpass"

	cat > "$RUNTIME_DIR/servers.json" <<-JSON
	{
	  "Servers": {
	    "1": {
	      "Name": "OneDev (local dev)",
	      "Group": "CraftGenie",
	      "Host": "postgres",
	      "Port": 5432,
	      "MaintenanceDB": "$POSTGRES_DB",
	      "Username": "$POSTGRES_USER",
	      "PassFile": "/pgpass",
	      "SSLMode": "prefer",
	      "Comment": "Generated by cg-dev.sh from craftgenie-dev/.env - edits here are overwritten."
	    }
	  }
	}
	JSON
}

# --------------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------------

wait_for_postgres() {
	info "Waiting for PostgreSQL to accept connections"
	for _ in $(seq 1 60); do
		if compose exec -T postgres pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
			ok "PostgreSQL is ready on localhost:$POSTGRES_PORT"
			return 0
		fi
		sleep 1
	done
	compose logs --tail 30 postgres >&2
	die "PostgreSQL did not become ready within 60s (logs above)"
}

cmd_up() {
	require_docker
	load_env
	write_runtime_files
	info "Starting PostgreSQL and pgAdmin"
	compose up -d
	wait_for_postgres
	echo
	ok "PostgreSQL  postgresql://$POSTGRES_USER@localhost:$POSTGRES_PORT/$POSTGRES_DB"
	ok "pgAdmin     http://localhost:$PGADMIN_PORT  ${DIM}(no login prompt; server pre-registered)${RESET}"
	echo
	printf '%sNext:%s ./cg-dev.sh run\n' "$BOLD" "$RESET"
}

cmd_down() {
	require_docker
	load_env
	info "Stopping containers (data is preserved)"
	compose down
	ok "Stopped. Data volumes kept - use 'destroy' to remove them."
}

cmd_destroy() {
	require_docker
	load_env
	warn "This deletes the PostgreSQL volume. Every OneDev project, issue and user in it is lost."
	read -r -p "Type 'destroy' to confirm: " reply
	[ "$reply" = "destroy" ] || die "Aborted."
	compose down -v
	rm -f "$RUNTIME_DIR/pgpass" "$RUNTIME_DIR/servers.json"
	ok "Containers and volumes removed."
}

cmd_reset_db() {
	require_docker
	load_env
	warn "This drops and recreates the '$POSTGRES_DB' database. All OneDev data is lost."
	read -r -p "Type 'reset' to confirm: " reply
	[ "$reply" = "reset" ] || die "Aborted."
	# Terminate open sessions first: DROP DATABASE fails while OneDev holds connections.
	compose exec -T postgres psql -U "$POSTGRES_USER" -d postgres -v ON_ERROR_STOP=1 <<-SQL
		SELECT pg_terminate_backend(pid) FROM pg_stat_activity
		 WHERE datname = '$POSTGRES_DB' AND pid <> pg_backend_pid();
		DROP DATABASE IF EXISTS "$POSTGRES_DB";
		CREATE DATABASE "$POSTGRES_DB" OWNER "$POSTGRES_USER";
	SQL
	ok "Database recreated. OneDev will run first-time setup on next start."
}

ensure_sandbox() {
	if [ ! -d "$SANDBOX_CONF" ]; then
		info "Development sandbox not built yet - running ./dev.sh build (first run takes a while)"
		"$ROOT/dev.sh" build
	fi
	[ -d "$SANDBOX_CONF" ] || die "Expected $SANDBOX_CONF after build, but it is missing"
}

cmd_configure() {
	load_env
	ensure_sandbox
	[ -f "$TEMPLATE_CONF" ] || die "Missing template: $TEMPLATE_CONF"

	local target="$SANDBOX_CONF/hibernate.properties"
	local url="jdbc:postgresql://localhost:$POSTGRES_PORT/$POSTGRES_DB"

	# Start from OneDev's own template and comment out whichever database it had
	# active, rather than writing a file from scratch. Upstream changes to the
	# shared Hibernate settings then carry over on their own.
	{
		sed -E 's/^[[:space:]]*(hibernate\.dialect|hibernate\.connection\.(driver_class|url|username|password))[[:space:]]*=/#&/' \
			"$TEMPLATE_CONF"
		cat <<-PROPS

			#---------------------------------------------------------------------
			# CraftGenie local development - PostgreSQL via craftgenie-dev/docker-compose.yml
			# Generated by cg-dev.sh. This file lives under target/ and is rewritten
			# on every 'cg-dev.sh configure' or 'cg-dev.sh run'; do not hand-edit it.
			#---------------------------------------------------------------------
			hibernate.dialect=io.onedev.server.persistence.PostgreSQLDialect
			hibernate.connection.driver_class=org.postgresql.Driver
			hibernate.connection.url=$url
			hibernate.connection.username=$POSTGRES_USER
			hibernate.connection.password=$POSTGRES_PASSWORD
		PROPS
	} > "$target"

	ok "OneDev configured for PostgreSQL"
	printf '     %s%s%s\n' "$DIM" "$url" "$RESET"
	printf '     %sdriver: site/lib/postgresql-*.jar (shipped with OneDev)%s\n' "$DIM" "$RESET"
}

cmd_run() {
	cmd_up
	cmd_configure

	# OneDev reads these on first start and completes its setup wizard from them, so a
	# fresh database comes up with an admin account instead of a setup page. They are
	# ignored once the root account exists, which makes re-running this harmless.
	export initial_user="$ONEDEV_INITIAL_USER"
	export initial_password="${ONEDEV_INITIAL_PASSWORD:-}"
	export initial_email="$ONEDEV_INITIAL_EMAIL"
	export initial_server_url="$ONEDEV_SERVER_URL"

	echo
	info "Starting OneDev on $ONEDEV_SERVER_URL"
	printf '     %sadmin account: %s / %s%s\n' "$DIM" "$ONEDEV_INITIAL_USER" "${ONEDEV_INITIAL_PASSWORD:-<unset>}" "$RESET"
	printf '     %sRun ./dev.sh build in another terminal to hot-load Java changes.%s\n\n' "$DIM" "$RESET"
	exec "$ROOT/dev.sh" run
}

cmd_test() {
	require_docker
	info "Running CraftGenie integration tests (PostgreSQL via Testcontainers)"
	# Its own throwaway container, so it neither needs nor disturbs the dev database.
	cd "$ROOT" && exec mvn -Pce -pl craftgenie-it test "$@"
}

cmd_psql() {
	require_docker
	load_env
	exec docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" \
		exec postgres psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" "$@"
}

cmd_logs() {
	require_docker
	load_env
	compose logs -f --tail 100 "$@"
}

cmd_pgadmin() {
	load_env
	local url="http://localhost:$PGADMIN_PORT"
	ok "pgAdmin: $url"
	printf '     %ssigned in as %s, server "OneDev (local dev)" already registered%s\n' \
		"$DIM" "$PGADMIN_EMAIL" "$RESET"
	if command -v xdg-open >/dev/null 2>&1; then
		xdg-open "$url" >/dev/null 2>&1 &
	elif command -v open >/dev/null 2>&1; then
		open "$url" >/dev/null 2>&1 &
	fi
}

cmd_status() {
	require_docker
	load_env
	info "Containers"
	compose ps || true
	echo
	info "Database"
	if compose exec -T postgres pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" >/dev/null 2>&1; then
		ok "reachable on localhost:$POSTGRES_PORT"
		local tables
		tables=$(compose exec -T postgres psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -tAc \
			"SELECT count(*) FROM information_schema.tables WHERE table_schema='public'" 2>/dev/null || echo "?")
		printf '     %s%s tables in public schema%s\n' "$DIM" "$tables" "$RESET"
	else
		warn "not reachable - run ./cg-dev.sh up"
	fi
	echo
	info "OneDev configuration"
	local target="$SANDBOX_CONF/hibernate.properties"
	if [ ! -f "$target" ]; then
		warn "sandbox not built - run ./cg-dev.sh configure"
	elif grep -q '^hibernate.connection.driver_class=org.postgresql.Driver' "$target"; then
		ok "pointed at PostgreSQL"
	else
		warn "still on the bundled HSQLDB - run ./cg-dev.sh configure"
	fi
}

usage() {
	cat <<-USAGE
		${BOLD}CraftGenie OneDev development launcher${RESET}

		OneDev runs on the host (hot reloading intact); PostgreSQL and pgAdmin run in Docker.

		${BOLD}Usage:${RESET} ./cg-dev.sh <command>

		${BOLD}Everyday${RESET}
		  run          Start dependencies, point OneDev at PostgreSQL, start OneDev
		  up           Start PostgreSQL + pgAdmin and wait until ready
		  down         Stop containers, keep all data
		  status       Show container, database and OneDev configuration state

		${BOLD}Testing${RESET}
		  test         Run CraftGenie integration tests against a throwaway PostgreSQL

		${BOLD}Database${RESET}
		  psql [args]  Open a psql shell on the OneDev database
		  pgadmin      Print the pgAdmin URL and open a browser
		  reset-db     Drop and recreate the database ${DIM}(destructive)${RESET}
		  logs [svc]   Follow container logs

		${BOLD}Setup${RESET}
		  configure    Rewrite the sandbox Hibernate config for PostgreSQL
		  destroy      Remove containers and data volumes ${DIM}(destructive)${RESET}

		Configuration lives in ${BOLD}craftgenie-dev/.env${RESET}, created from .env.example on first run.
	USAGE
}

case "${1:-}" in
	up)        shift; cmd_up "$@" ;;
	test)      shift; cmd_test "$@" ;;
	down)      shift; cmd_down "$@" ;;
	run)       shift; cmd_run "$@" ;;
	configure) shift; cmd_configure "$@" ;;
	psql)      shift; cmd_psql "$@" ;;
	pgadmin)   shift; cmd_pgadmin "$@" ;;
	logs)      shift; cmd_logs "$@" ;;
	status)    shift; cmd_status "$@" ;;
	reset-db)  shift; cmd_reset_db "$@" ;;
	destroy)   shift; cmd_destroy "$@" ;;
	""|-h|--help|help) usage ;;
	*)         usage >&2; exit 1 ;;
esac
